
-- Create users table
CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) DEFAULT '',
    `email` VARCHAR(255) UNIQUE,
    `password` VARCHAR(255),
    `status` TINYINT(1) DEFAULT 1, 
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL
);

-- Create profiles table
CREATE TABLE IF NOT EXISTS `profiles` (
    `id` BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `img` TEXT DEFAULT NULL,
    `website` VARCHAR(255) DEFAULT NULL,
    `user_id` BIGINT,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
);

-- Create tags table
CREATE TABLE IF NOT EXISTS `tags` (
    `id` BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `status` TINYINT(1) DEFAULT 1, 
    `parent` INT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL
);

-- Create posts table
CREATE TABLE IF NOT EXISTS `posts` (
    `id` BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `status` TINYINT(1) DEFAULT 1, 
    `img` TEXT DEFAULT NULL,
    `des` TEXT DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL
);

-- Pivot table for tags and posts (many-to-many relationship)
CREATE TABLE IF NOT EXISTS `tag_posts` (
    `id` BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `tag_id` BIGINT NOT NULL,
    `post_id` BIGINT NOT NULL,
    FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) ON DELETE CASCADE
);

-- Alter tables
ALTER TABLE `users`
ADD COLUMN `last_login` DATETIME DEFAULT NULL;

ALTER TABLE `profiles`
ADD COLUMN `bio` TEXT DEFAULT NULL;
